CREATE DATABASE SERVICE_BASKET_DB2;

CREATE TABLE REGISTRATION_TABLE
(
FULLNAME VARCHAR (100) NOT NULL,
USERNAME VARCHAR (100) NOT NULL,
PASS VARCHAR (100) NOT NULL,
EMAIL VARCHAR (100) NOT NULL,
PHONE VARCHAR (100) NOT NULL
);

SELECT * FROM REGISTRATION_TABLE;
